name: Update README

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README stats
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" -o github_stats.svg https://github-readme-stats.vercel.app/api?username=0asaca0rum0&show_icons=true&theme=radical&count_private=true
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" -o top_langs.svg https://github-readme-stats.vercel.app/api/top-langs/?username=0asaca0rum0&layout=compact&theme=radical
          curl -o github_streak.svg https://github-readme-streak-stats.herokuapp.com/?user=0asaca0rum0&theme=radical
      - name: Commit updated README
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add github_stats.svg top_langs.svg github_streak.svg
          git commit -m "Update README stats"
          git push
